volumes:
  postgres_data:
  uwsgi_socket:
services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - ~/.pg/pg_data/flask-yt:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "54321:5432" 
  flask:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: flask
    volumes:
      - ~/.uploads/images/flask-yt:/app/app/static/upload
      - uwsgi_socket:/tmp
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - postgres
    expose:
      - 8081
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx/
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - flask
    volumes:
      - uwsgi_socket:/tmp
    ports:
      - "8081:80"
